name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Book
      id: book
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Book
        setup-command: ''
        command: mvn -Dtest=BookTest test
        timeout: 10
        max-score: 50
    - name: Borrow Record
      id: borrow-record
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Borrow Record
        setup-command: ''
        command: mvn -Dtest=BorrowRecordTest test
        timeout: 10
        max-score: 50
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        BOOK_RESULTS: "${{steps.book.outputs.result}}"
        BORROW-RECORD_RESULTS: "${{steps.borrow-record.outputs.result}}"
      with:
        runners: book,borrow-record
